learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

#TEMPLATE TAGGING

app_name = 'basic_app'

urlpatterns=[
    url(r'^relative/$',views.relative,name='relative'),
    url(r'^other/$',views.other,name='other')
]

learning_templates/learning_templates/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/',include('basic_app.urls')),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {'text':"Hello World !!","number":999}
    return render(request,'basic_app/index.html',context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base Html</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'index' %}" class="navbar-brand">Brand</a></li>
          <li><a href="{% url 'basic_app:other' %}" class="navbar-link">Other</a></li>
          <li><a href="{% url 'admin:index' %}" class="navbar-link">Admin</a></li>
        </ul>

      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      <!-- Everything outside this block will be inherited if you entend -->

      {% endblock %}
    </div>

  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load my_extras %}

  {% block body_block %}
    <h1>Welcome to the INDEX page</h1>
    <h2>Goto basic_app/relative </h2>
    <h2>{{ text|cu:'Worl' }}</h2>
    <h2>{{ number|add:'21' }}</h2>
  {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block%}
    <h1>Welcome to OTHEr template</h1>
    <h2>This is an example of template inheritance</h2>
  {% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Relaive</title>
  </head>
  <body>
    <h1>This is RELATIVE</h1>
    <a href="{% url 'basic_app:other' %}">Link to OTHER </a>
    <a href="{% url 'admin:index' %}">Link to admin</a>
    <a href="{% url 'index' %}">Home Page</a>
  </body>
</html>